site_name: WEAVE-IO
theme: readthedocs
nav:
  - Outline: index.md
  - Setup: setup.md
  - Quickstart: quickstart.md
  - 'Implementation Details':
      - 'The Graph Database': implementation-details/graph-database.md
      - 'WEAVE-IO Schema': implementation-details/schema.md
      - 'Writing to WEAVE-IO': implementation-details/writing.md