name: Publish to PyPi

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: Build and publish distributions to PyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: bad cryptography
        run: export CRYPTOGRAPHY_DONT_BUILD_RUST=1
      - name: Build
        run: python setup.py sdist bdist_wheel --universal
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true